
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#521800",
        "surface-container": "#eeeeef",
        "secondary": "#5e5e62",
        "on-surface": "#1a1c1d",
        "on-error-container": "#93000a",
        "tertiary-container": "#8e939d",
        "primary-fixed": "#ffdbce",
        "surface": "#f9f9fa",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#424750",
        "surface-tint": "#a73a00",
        "surface-container-high": "#e8e8e9",
        "on-secondary-fixed": "#1b1b1f",
        "on-background": "#1a1c1d",
        "outline": "#8f7065",
        "on-primary-fixed": "#370e00",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#5b4137",
        "tertiary-fixed-dim": "#c2c6d2",
        "surface-dim": "#dadadb",
        "primary": "#a73a00",
        "on-tertiary-container": "#272c34",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#802a00",
        "surface-container-low": "#f3f3f4",
        "secondary-fixed": "#e3e2e6",
        "on-tertiary-fixed": "#171c24",
        "secondary-container": "#e3e2e6",
        "on-secondary-container": "#646468",
        "background": "#f9f9fa",
        "tertiary": "#595f68",
        "surface-variant": "#e2e2e3",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f3132",
        "surface-bright": "#f9f9fa",
        "surface-container-highest": "#e2e2e3",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#dee2ee",
        "error": "#ba1a1a",
        "inverse-primary": "#ffb59a",
        "inverse-on-surface": "#f1f0f1",
        "outline-variant": "#e4beb1",
        "primary-container": "#ff5c00",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c7c6ca",
        "primary-fixed-dim": "#ffb59a",
        "on-secondary-fixed-variant": "#46464a",
        brand: {
          orange: '#FF5C00',
          hover: '#E04F00',
          dark: '#111827',
          grayBg: '#EDEDED',
          border: '#D2D6DC',
          panel: '#F7F7F8'
        }
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "gutter": "0px"
      },
      fontFamily: {
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "label-code": ["Space Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-mono": ["Space Mono", "monospace"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "display-xl-mobile": ["Space Grotesk", "sans-serif"],
        mono: ['"JetBrains Mono"', 'monospace'],
        sans: ['"Space Grotesk"', 'sans-serif'],
        display: ['"Chakra Petch"', 'sans-serif']
      },
      fontSize: {
        "body-sm": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-code": ["11px", {"lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["15px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-mono": ["12px", {"lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "500"}],
        "display-xl": ["72px", {"lineHeight": "76px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "display-xl-mobile": ["40px", {"lineHeight": "44px", "letterSpacing": "-0.03em", "fontWeight": "700"}]
      }
    }
  }
};
